version: '3.7'
services:
  backend:
    build: ./backend
    command: ["python3", "run.py"]
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - backend