version: '3.7'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "run.py"]
    volumes:
      - "./backend:/app"
    ports:
      - "5000:5000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "start"]
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    depends_on:
      - backend
